"use client";

import {
    ClerkProvider,
    SignedIn,
    SignedOut,
    SignInButton,
    UserButton,
} from "@clerk/nextjs";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

export const metadata: Metadata = {
    title: "Clerk Next.js Quickstart",
    description: "Generated by create next app",
};

export default function Navbar() {
    const [role, setRole] = useState<string>("user");

    // Fetch user role from API
    useEffect(() => {
        fetch("/api/me")
            .then((res) => res.json())
            .then((data) => setRole(data.role))
            .catch(() => setRole("user"));
    }, []);

    return (
        <ClerkProvider>
            <div className="w-full max-w-7xl mx-auto flex items-center justify-between py-6 relative h-auto">
                {/* Logo */}
                <div className="flex items-center justify-between w-1/12 relative h-10">
                    <Link href="/" className="relative w-full h-full">
                        <Image
                        src="/logoBTL.ico"
                        alt="Mon icône"
                        fill
                        className="object-contain cursor-pointer"
                        />
                    </Link>
                </div>

                <div className="w-2/12"></div>

                {/* Navbar links */}
                <nav className="w-6/12 bg-[#111461]/30 rounded-xl px-6 py-3 flex justify-center space-x-16">
                    <a
                        href="/matchs"
                        className="text-white text-lg font-medium hover:text-red-400 transition-colors"
                    >
                        Matchs
                    </a>
                    <a
                        href="/results"
                        className="text-white text-lg font-medium hover:text-red-400 transition-colors"
                    >
                        Results
                    </a>
                    <a
                        href="/about"
                        className="text-white text-lg font-medium hover:text-red-400 transition-colors"
                    >
                        About
                    </a>

                    {/* Admin-only link */}
                    {role === "admin" && (
                        <a
                            href="/admin"
                            className="text-red-400 text-lg font-bold hover:text-white transition-colors"
                        >
                            Gestion
                        </a>
                    )}
                </nav>

                <div className="w-1/12"></div>

                {/* Auth buttons */}
                <div className="flex w-2/12 justify-center items-center gap-3">
                    <SignedOut>
                        <SignInButton>
                            <button
                                type="button"
                                className="bg-[#2621BF] w-full text-white rounded-xl font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-6 cursor-pointer hover:bg-[#3c36e0] transition-colors"
                            >
                                Sign In
                            </button>
                        </SignInButton>
                    </SignedOut>
                    <SignedIn>
                        <UserButton />
                    </SignedIn>
                </div>
            </div>
        </ClerkProvider>
    );
}
